local module = require(script.Parent:FindFirstChild(".pesde"):FindFirstChild("elttob_fusion@0.3.0"):FindFirstChild("fusion"))
export type Animatable  = module.Animatable 
export type UsedAs<T> = module.UsedAs<T>
export type Child  = module.Child 
export type Computed<T> = module.Computed<T>
export type Contextual<T> = module.Contextual<T>
export type GraphObject  = module.GraphObject 
export type For<KO, VO> = module.For<KO, VO>
export type Observer  = module.Observer 
export type PropertyTable  = module.PropertyTable 
export type Scope<Constructors = Fusion> = module.Scope<Constructors >
export type ScopedObject  = module.ScopedObject 
export type SpecialKey  = module.SpecialKey 
export type Spring<T> = module.Spring<T>
export type StateObject<T> = module.StateObject<T>
export type Task  = module.Task 
export type Tween<T> = module.Tween<T>
export type Use  = module.Use 
export type Value<T, S = T> = module.Value<T, S >
export type Version  = module.Version 
return module