name = "killergg/axis"
version = "0.2.3-rc.2"
description = "An agnostic, simple and versatile input library for ECS"
license = "MIT"
authors = ["NeonD00m", "As8D"]
repository = "https://github.com/neond00m/Axis"
private = false
includes = ["pesde.toml", "README.md", "LICENSE", "src/**"]

[target]
environment = "roblox"
lib = "src/init.luau"
build_files = ["src"]

[dev_dependencies.rojo]
name = "pesde/rojo"
version = "^7.4.4"
index = "https://github.com/pesde-pkg/index"
target = "lune"

[dev_dependencies.scripts]
name = "pesde/scripts_rojo"
version = "^0.1.0"
index = "https://github.com/pesde-pkg/index"
target = "lune"
