name = "neond00m/replecs"
version = "0.2.0-dev.1"
description = "Replecs with hooks plus some configurations"
license = "MIT"
authors = ["PepeElToro41", "NeonD00m", "As8d"]
repository = "https://github.com/PepeElToro41/replecs"
private = false
includes = ["pesde.toml", "README.md", "LICENSE.md", "src/**"]

[target]
environment = "roblox"
lib = "src/init.luau"
build_files = ["src"]

[dependencies.jecs]
wally = "wally#ukendio/jecs"
version = "^0.9.0-rc.8"
index = "https://github.com/UpliftGames/wally-index"
